## Name of the Job 
#PBS -N bubble-sort

## Queue it will run in
#PBS -q devel

## Select 1 node with 40 processors
#PBS -l select=1:ncpus=40:vntype=cray_compute

## Pack all of them in 1 node
#PBS -l place=pack

## Join output and error in a single file
#PBS -j oe

## Export the environment vaiables from your shell
#PBS -V

cd $PBS_O_WORKDIR

time aprun -n 1 -d 40 ./bubble-sort 1 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 2 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 4 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 8 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 16 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 20 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 24 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 28 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 32 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 40 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 60 200000 10 2
time aprun -n 1 -d 40 ./bubble-sort 80 200000 10 2

time aprun -n 1 -d 20 ./bubble-sort 1 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 2 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 4 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 8 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 16 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 20 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 24 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 28 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 32 200000 10 2
time aprun -n 1 -d 20 ./bubble-sort 40 200000 10 2

time aprun -n 1 -d 10 ./bubble-sort 1 200000 10 2
time aprun -n 1 -d 10 ./bubble-sort 2 200000 10 2
time aprun -n 1 -d 10 ./bubble-sort 4 200000 10 2
time aprun -n 1 -d 10 ./bubble-sort 8 200000 10 2
time aprun -n 1 -d 10 ./bubble-sort 16 200000 10 2
time aprun -n 1 -d 10 ./bubble-sort 20 200000 10 2
